name: build cv
on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build cv
        env:
          DOCKER_IMAGE: "ultral/docker_latex:latest"
        run: |
          docker run --rm -w /dir -i -v ${PWD}/example:/dir ${DOCKER_IMAGE} pdflatex example.tex
      - name: Create GitHub release with artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            example/example.pdf
          name: "Build ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

